import { createHash, randomUUID } from "node:crypto";
import path from "node:path";
import type pg from "pg";
import { getDbPool, withTransaction } from "./db/pool";
import { getStorageEngine } from "./storage/engine";
import { config } from "./config";
import { sanitizeFilename } from "./security";
import { audit } from "./audit";
import { DEPARTMENTS, getDepartment } from "./department-registry";
import { classifyLegacyPath, compareCandidate, needsVerification, type ScannerComparison } from "./legacy-scanner-core";
import { createLegacySourceAdapter, FilesystemAdapter, type SourceAdapter, type SourceCandidate } from "./legacy-source-adapters";

export const LEGACY_NOTICEBOARD_ROOT = process.env.LEGACY_NOTICEBOARD_ROOT ?? "/mnt/legacy-noticeboards/noticeboards";
const VERIFY_MS = Number(process.env.LEGACY_SCANNER_VERIFY_INTERVAL_HOURS ?? 168) * 3600_000;
const LOCK = 172917;
export type ScanMode = "DRY_RUN" | "IMPORT";
export type Candidate = SourceCandidate;
export type Comparison = ScannerComparison;
export { classifyLegacyPath, compareCandidate };
export async function discoverLegacyFiles(source = LEGACY_NOTICEBOARD_ROOT) { return new FilesystemAdapter(source).discover(); }

const scannerIdentity = (p: string) => createHash("sha256").update(p).digest("hex");
const itemIdentity = (p: string, h: string) => `scanner:${createHash("sha256").update(`${p}\0${h}`).digest("hex")}`;
function mime(name: string) { return ({ ".pdf": "application/pdf", ".txt": "text/plain", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png" } as Record<string, string>)[path.extname(name).toLowerCase()] ?? "application/octet-stream"; }

async function hashSource(adapter: SourceAdapter, candidate: Candidate) {
  const source = await adapter.open(candidate); const hash = createHash("sha256"); let size = 0;
  for await (const chunk of source.stream as AsyncIterable<Buffer | Uint8Array | string>) { const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); size += bytes.length; hash.update(bytes); }
  if (candidate.sizeBytes > 0 && size !== candidate.sizeBytes) throw new Error("Legacy source size changed while being read");
  return { sha256: hash.digest("hex"), size, mtimeMs: candidate.mtimeMs };
}

async function publish(adapter: SourceAdapter, candidate: Candidate, digest: string, actor: string) {
  const db = getDbPool(); const identity = itemIdentity(candidate.relativePath, digest); const known = await db.query<{ id: string }>("SELECT id FROM files WHERE legacy_item_id=$1", [identity]); if (known.rows[0]) return known.rows[0].id;
  const engine = getStorageEngine(); await engine.assertUploadCapacity(candidate.sizeBytes, config.largeUploadBytes, config.storageReserveBytes); const { stagingPath } = await engine.createStagingFile(); let storageKey: string | undefined;
  try {
    const source = await adapter.open(candidate); const written = await engine.writeStream(source.stream, stagingPath); if (candidate.sizeBytes > 0 && written.sizeBytes !== candidate.sizeBytes || written.sha256 !== digest) throw new Error("Legacy source changed while being read");
    await engine.finalizeWrite(stagingPath, written.sizeBytes, digest); storageKey = engine.createStorageKey(); await engine.publish(storageKey, stagingPath); if (!await engine.verify(storageKey, written.sizeBytes, digest)) throw new Error("Published legacy object verification failed");
    const fileId = randomUUID(), versionId = randomUUID();
    try { await withTransaction(async client => { await client.query("INSERT INTO files (id,original_name,mime_type,size_bytes,sha256,storage_key,state,created_by,origin_type,legacy_item_id,legacy_department,legacy_relative_path) VALUES ($1,$2,$3,$4,$5,$6,'ACTIVE',$7,'LEGACY_IMPORT',$8,$9,$10)", [fileId, sanitizeFilename(path.basename(candidate.relativePath)), candidate.contentType ?? mime(candidate.relativePath), written.sizeBytes, Buffer.from(digest, "hex"), storageKey, actor, identity, candidate.department, candidate.relativePath]); await client.query("INSERT INTO file_versions (id,file_id,version_number,storage_key,mime_type,size_bytes,sha256,created_by) VALUES ($1,$2,1,$3,$4,$5,$6,$7)", [versionId, fileId, storageKey, candidate.contentType ?? mime(candidate.relativePath), written.sizeBytes, Buffer.from(digest, "hex"), actor]); await client.query("UPDATE files SET current_version_id=$1 WHERE id=$2", [versionId, fileId]); }); } catch (error) { await engine.quarantine(storageKey); throw error; }
    await audit("LEGACY_SCANNER_FILE_IMPORTED", actor, "file", fileId, { legacyRelativePath: candidate.relativePath, sha256: digest }); return fileId;
  } catch (error) { if (!storageKey) try { await engine.quarantinePartial(stagingPath); } catch {} throw error; }
}

type Prior = { id: string; legacy_relative_path: string; source_size_bytes: string | null; source_mtime_ms: string | null; source_sha256: string | null; source_verified_at: string | null; file_id: string | null; status: string };
type Counts = { discovered: number; new: number; changed: number; missing: number; unchanged: number; imported: number; failed: number; skipped: number; processed: number };
async function stale(client: pg.PoolClient) { await client.query("UPDATE legacy_scanner_runs SET status='INTERRUPTED',completed_at=NOW(),error_message='Scanner lease expired',heartbeat_at=NOW() WHERE status='RUNNING' AND heartbeat_at<NOW()-INTERVAL '15 minutes'"); }
async function progress(client: pg.PoolClient, id: string, total: number, c: Counts, last: string | null) { await client.query("UPDATE legacy_scanner_runs SET heartbeat_at=NOW(),total_count=$2,processed_count=$3,last_processed_path=$4,discovered_count=$5,new_count=$6,changed_count=$7,missing_count=$8,unchanged_count=$9,imported_count=$10,failed_count=$11,skipped_count=$12 WHERE id=$1", [id, total, c.processed, last, c.discovered, c.new, c.changed, c.missing, c.unchanged, c.imported, c.failed, c.skipped]); }

export async function startLegacyScan(actor: string, mode: ScanMode) { const client = await getDbPool().connect(); try { await stale(client); const lock = await client.query<{ locked: boolean }>("SELECT pg_try_advisory_lock($1) locked", [LOCK]); if (!lock.rows[0]?.locked) throw new Error("A scanner run is already active"); const id = randomUUID(); await client.query("INSERT INTO legacy_scanner_runs(id,requested_by,mode,status)VALUES($1,$2,$3,'RUNNING')", [id, actor, mode]); void execute(client, id, actor, mode); return id; } catch (error) { client.release(); throw error; } }
async function execute(client: pg.PoolClient, id: string, actor: string, mode: ScanMode) {
  const c: Counts = { discovered: 0, new: 0, changed: 0, missing: 0, unchanged: 0, imported: 0, failed: 0, skipped: 0, processed: 0 }; const adapter = createLegacySourceAdapter();
  try { const list = await adapter.discover(); c.discovered = list.length; const [items, files] = await Promise.all([client.query<Prior>("SELECT id,legacy_relative_path,source_size_bytes::text,source_mtime_ms::text,encode(source_sha256,'hex') source_sha256,source_verified_at::text,file_id,status FROM legacy_scanner_items"), client.query<{ id: string; legacy_relative_path: string; size_bytes: string; sha256: string }>("SELECT id,legacy_relative_path,size_bytes::text,encode(sha256,'hex') sha256 FROM files WHERE origin_type='LEGACY_IMPORT' AND state='ACTIVE' AND legacy_relative_path IS NOT NULL")]); const prior = new Map(items.rows.map(row => [row.legacy_relative_path, row])); const existing = new Map<string, { id: string; size_bytes: string; sha256: string }[]>(); for (const file of files.rows) existing.set(file.legacy_relative_path, [...(existing.get(file.legacy_relative_path) ?? []), file]); const seen = new Set<string>();
    for (const candidate of list) { seen.add(candidate.relativePath); const previous = prior.get(candidate.relativePath); const comparison = compareCandidate(candidate, previous); c[comparison]++; let digest: string | null = null; let fileId = previous?.file_id ?? null; let status = "OBSERVED"; let error: string | null = null; try { if (comparison === "skipped") status = "UNCLASSIFIABLE"; else if (needsVerification(comparison, previous?.status, previous?.source_verified_at, Date.now(), VERIFY_MS)) { const verified = await hashSource(adapter, candidate); digest = verified.sha256; const matching = existing.get(candidate.relativePath)?.find(file => Number(file.size_bytes) === candidate.sizeBytes && file.sha256 === digest); if (!previous && matching) { c.new--; c.unchanged++; fileId = matching.id; status = "IMPORTED"; } else if (previous?.source_sha256 === digest && previous.file_id) { c[comparison]--; c.unchanged++; status = "IMPORTED"; } else { if (!previous && existing.has(candidate.relativePath)) { c.new--; c.changed++; } status = mode === "IMPORT" ? "IMPORTED" : "PENDING_IMPORT"; if (mode === "IMPORT") { fileId = await publish(adapter, candidate, digest, actor); c.imported++; } } } else status = previous?.file_id ? "IMPORTED" : "PENDING_IMPORT"; } catch (e) { c.failed++; status = "FAILED"; error = e instanceof Error ? e.message : "Scanner failure"; }
      await client.query("INSERT INTO legacy_scanner_items(id,scanner_identity,legacy_relative_path,department,source_size_bytes,source_mtime_ms,source_sha256,source_verified_at,file_id,status,last_seen_at,last_run_id,error_message)VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $7 IS NULL THEN NULL ELSE NOW() END,$8,$9,NOW(),$10,$11) ON CONFLICT(legacy_relative_path)DO UPDATE SET department=EXCLUDED.department,source_size_bytes=EXCLUDED.source_size_bytes,source_mtime_ms=EXCLUDED.source_mtime_ms,source_sha256=COALESCE(EXCLUDED.source_sha256,legacy_scanner_items.source_sha256),source_verified_at=COALESCE(EXCLUDED.source_verified_at,legacy_scanner_items.source_verified_at),file_id=COALESCE(EXCLUDED.file_id,legacy_scanner_items.file_id),status=EXCLUDED.status,last_seen_at=NOW(),last_run_id=EXCLUDED.last_run_id,error_message=EXCLUDED.error_message,updated_at=NOW()", [previous?.id ?? randomUUID(), scannerIdentity(candidate.relativePath), candidate.relativePath, candidate.department, candidate.sizeBytes, candidate.mtimeMs, digest ? Buffer.from(digest, "hex") : null, fileId, status, id, error]); c.processed++; if (c.processed % 10 === 0) await progress(client, id, list.length, c, candidate.relativePath); }
    const missing = items.rows.filter(row => !seen.has(row.legacy_relative_path)); c.missing = missing.length; if (missing.length) await client.query("UPDATE legacy_scanner_items SET status='MISSING',last_run_id=$1,updated_at=NOW() WHERE legacy_relative_path=ANY($2::text[])", [id, missing.map(row => row.legacy_relative_path)]); await progress(client, id, list.length, c, list.at(-1)?.relativePath ?? null); await client.query("UPDATE legacy_scanner_runs SET status='SUCCEEDED',completed_at=NOW() WHERE id=$1", [id]); await audit("LEGACY_SCANNER_COMPLETED", actor, "legacy_scanner_run", null, { runId: id, mode, ...c });
  } catch (e) { await client.query("UPDATE legacy_scanner_runs SET status='FAILED',completed_at=NOW(),error_message=$2 WHERE id=$1", [id, e instanceof Error ? e.message : "Unknown scanner failure"]); } finally { try { await client.query("SELECT pg_advisory_unlock($1)", [LOCK]); } finally { client.release(); } }
}
export async function scannerStatus(id?: string) { const db = getDbPool(); const runs = await db.query(id ? "SELECT * FROM legacy_scanner_runs WHERE id=$1" : "SELECT * FROM legacy_scanner_runs ORDER BY started_at DESC LIMIT 10", id ? [id] : []); const failures = await db.query("SELECT id,legacy_relative_path,error_message,updated_at FROM legacy_scanner_items WHERE status='FAILED' ORDER BY updated_at DESC LIMIT 30"); return { runs: runs.rows, failures: failures.rows, departments: DEPARTMENTS.map(d => d.slug) }; }
export async function retryLegacyScannerItem(id: string, actor: string) { const client = await getDbPool().connect(); try { await stale(client); const lock = await client.query<{ locked: boolean }>("SELECT pg_try_advisory_lock($1) locked", [LOCK]); if (!lock.rows[0]?.locked) throw new Error("A scanner run is already active"); const result = await client.query<Prior>("SELECT id,legacy_relative_path,source_size_bytes::text,source_mtime_ms::text,encode(source_sha256,'hex') source_sha256,source_verified_at::text,file_id,status FROM legacy_scanner_items WHERE id=$1 AND status='FAILED'", [id]); const item = result.rows[0]; if (!item || !getDepartment(item.legacy_relative_path.split("/")[0])) throw new Error("Retryable scanner item not found"); const adapter = createLegacySourceAdapter(); const candidate = await adapter.resolve(item.legacy_relative_path); const verified = await hashSource(adapter, candidate); const fileId = await publish(adapter, candidate, verified.sha256, actor); await client.query("UPDATE legacy_scanner_items SET source_size_bytes=$1,source_mtime_ms=$2,source_sha256=$3,source_verified_at=NOW(),file_id=$4,status='IMPORTED',error_message=NULL,last_seen_at=NOW(),updated_at=NOW() WHERE id=$5", [verified.size, verified.mtimeMs, Buffer.from(verified.sha256, "hex"), fileId, id]); } finally { try { await client.query("SELECT pg_advisory_unlock($1)", [LOCK]); } finally { client.release(); } } }
