import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createServer, type Server } from "node:http";
import { HttpDirectoryAdapter } from "./legacy-source-adapters";

let server: Server; let port = 0;
let requests: { method: string; url: string }[] = []; let boundedActive = 0; let boundedPeak = 0;
beforeAll(async () => { server = createServer((req, res) => { const url = decodeURIComponent(req.url ?? "/"); requests.push({ method: req.method ?? "", url }); if (url === "/root/") { res.setHeader("content-type", "text/html"); res.end('<a href="nested/">nested</a><a href="hello%20world.pdf">file</a><a href="~$temp.xlsx">temp</a><a href="../escape.txt">escape</a><a href="http://evil.example/x">external</a>'); return; } if (url === "/root/nested/") { res.setHeader("content-type", "text/html"); res.end('<a href="report.docx">report</a>'); return; } if (url === "/root/hello world.pdf") { res.setHeader("content-type", "application/pdf"); res.setHeader("content-length", "5"); res.setHeader("last-modified", "Wed, 01 Jan 2025 00:00:00 GMT"); res.setHeader("etag", '"abc"'); res.end("hello"); return; } if (url === "/root/nested/report.docx") { res.setHeader("content-type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"); res.end("report"); return; } if (url === "/root/~$temp.xlsx") { res.end("temp"); return; } if (url === "/root/redirect") { res.statusCode = 302; res.setHeader("location", "http://evil.example/file"); res.end(); return; } if (url === "/root/slow") { setTimeout(() => res.end("slow"), 100); return; } if (url === "/bounded/") { res.end(Array.from({ length: 5 }, (_, index) => `<a href="file-${index}.txt">file</a>`).join("")); return; } if (url.startsWith("/bounded/file-")) { boundedActive++; boundedPeak = Math.max(boundedPeak, boundedActive); res.setHeader("content-length", "1"); setTimeout(() => { boundedActive--; res.end("x"); }, 20); return; } if (url === "/fallback/") { res.end('<a href="file.txt">file</a>'); return; } if (url === "/fallback/file.txt" && req.method === "HEAD") { res.statusCode = 405; res.end(); return; } if (url === "/fallback/file.txt") { res.setHeader("content-length", "4"); res.setHeader("content-type", "text/plain"); res.end("file"); return; } res.statusCode = 404; res.end(); }).listen(0); await new Promise<void>(resolve => server.once("listening", () => { port = (server.address() as { port: number }).port; resolve(); })); });
afterAll(async () => { await new Promise<void>(resolve => server.close(() => resolve())); });
describe("HTTP legacy source adapter", () => {
  it("discovers nested directories, decodes URLs, filters temporary files, and extracts metadata", async () => { const adapter = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/root/`, maxResponseBytes: 10000 }); const files = await adapter.discover(); expect(files.map(file => file.relativePath)).toEqual(["hello world.pdf", "nested/report.docx"]); expect(files[0].contentType).toBe("application/pdf"); expect(files[0].etag).toBe('"abc"'); expect(files[0].mtimeMs).toBeGreaterThan(0); });
  it("uses HEAD for file metadata discovery", async () => { requests = []; const adapter = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/root/`, maxResponseBytes: 10000 }); await adapter.discover(); expect(requests.filter(request => request.url.includes("hello world.pdf") || request.url.includes("report.docx")).map(request => request.method)).toEqual(["HEAD", "HEAD"]); });
  it("bounds concurrent file metadata requests and preserves ordering", async () => { requests = []; boundedPeak = 0; const adapter = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/bounded/`, concurrency: 2 }); const files = await adapter.discover(); expect(boundedPeak).toBeLessThanOrEqual(2); expect(files.map(file => file.relativePath)).toEqual(["file-0.txt", "file-1.txt", "file-2.txt", "file-3.txt", "file-4.txt"]); });
  it("falls back to GET when HEAD is unsupported", async () => { requests = []; const adapter = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/fallback/` }); const files = await adapter.discover(); expect(files[0].sizeBytes).toBe(4); expect(requests.filter(request => request.url === "/fallback/file.txt").map(request => request.method)).toEqual(["HEAD", "GET"]); });
  it("streams file content and rejects cross-origin redirects", async () => { const adapter = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/root/` }); const candidate = (await adapter.discover())[0]; const opened = await adapter.open(candidate); let value = ""; for await (const chunk of opened.stream as AsyncIterable<Buffer>) value += chunk.toString(); expect(value).toBe("hello"); await expect(adapter.open({ ...candidate, sourceRef: `http://127.0.0.1:${port}/root/redirect` })).rejects.toThrow(/escaped|redirect/); });
  it("enforces response limits and request timeouts", async () => { const limited = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/root/`, maxResponseBytes: 10 }); await expect(limited.discover()).rejects.toThrow(/exceeds configured limit/); const timeout = new HttpDirectoryAdapter({ rootUrl: `http://127.0.0.1:${port}/root/`, timeoutMs: 20 }); await expect(timeout.open({ relativePath: "slow", absolutePath: "", sourceRef: `http://127.0.0.1:${port}/root/slow`, sizeBytes: 0, mtimeMs: 0, department: null })).rejects.toThrow(); });
});
